### ISSUE TITLE
About error ocurred

### ISSUE THREAD

**Issue by mozgbrasil** [Abdallah-khalil/NodeJsWithPassport#2]
Good morning my friends

About error ocurred

I'm testing this project and the following error is being returned

    $ npm run start
    Debugger attached.

    > nest-typescript-starter@1.0.0 start /workspace/Abdallah-khalil_NodeJsWithPassport
    > npm run start:watch

    Debugger attached.

    > nest-typescript-starter@1.0.0 start:watch /workspace/Abdallah-khalil_NodeJsWithPassport
    > nodemon

    Debugger attached.
    [nodemon] 1.19.4
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching dir(s): src/**/*
    [nodemon] watching extensions: ts
    [nodemon] starting `node ./index`
    Debugger attached.

    /workspace/Abdallah-khalil_NodeJsWithPassport/node_modules/ts-node/src/index.ts:307
            throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                  ^
    TSError: ⨯ Unable to compile TypeScript
    src/server.ts (12,12): Property 'set' does not exist on type 'Application'. (2339)
    src/server.ts (13,12): Property 'set' does not exist on type 'Application'. (2339)
    src/server.ts (16,12): Property 'use' does not exist on type 'Application'. (2339)
    src/server.ts (17,12): Property 'use' does not exist on type 'Application'. (2339)
    src/server.ts (19,12): Property 'use' does not exist on type 'Application'. (2339)
    src/server.ts (21,12): Property 'use' does not exist on type 'Application'. (2339)
        at getOutput (/workspace/Abdallah-khalil_NodeJsWithPassport/node_modules/ts-node/src/index.ts:307:15)
        at /workspace/Abdallah-khalil_NodeJsWithPassport/node_modules/ts-node/src/index.ts:336:16
        at Object.compile (/workspace/Abdallah-khalil_NodeJsWithPassport/node_modules/ts-node/src/index.ts:498:11)
        at Module.m._compile (/workspace/Abdallah-khalil_NodeJsWithPassport/node_modules/ts-node/src/index.ts:392:43)
        at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Object.require.extensions.<computed> [as .ts] (/workspace/Abdallah-khalil_NodeJsWithPassport/node_modules/ts-node/src/index.ts:395:12)
        at Module.load (internal/modules/cjs/loader.js:950:32)
        at Function.Module._load (internal/modules/cjs/loader.js:790:12)
        at Module.require (internal/modules/cjs/loader.js:974:19)
        at require (internal/modules/cjs/helpers.js:93:18)
    Waiting for the debugger to disconnect...
    [nodemon] app crashed - waiting for file changes before starting...

Thanks in advance to everyone who can contribute.

**Comment by preeti-3** [comment]
same error.
